name: call-locus2
description: This is an action that calls locus to help find bug inducing commits
author: Justin Ruffin, Rohan Repala, Dhruv Sapra, Bharath Mahendran
branding:
  icon: 'thumbs-up'
  color: 'white'
          
runs:
  using: "composite"
  steps:
    - id: call-api
      run: |
        echo "::set-output name=responseInfo::$(curl -d '{"option": "value"}' -H "Content-Type: application/json" -X POST https://postman-echo.com/post)"
      shell: bash
