name: Call Locus 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
      
  curl-stmt:
    runs-on: ubuntu-latest
    outputs:
      response_info: ${{ steps.get-response.outputs.response }}
    steps: 
      - id: get-response
        run: |
          token=$(curl -X POST http://104.131.188.205:5000/locus -H "Content-Type: application/json" -d "{ \"title\":\"${{ github.event.issue.title }}\", \"body\":\"${{ github.event.issue.body }}\", \"url\":\"${{ github.repositoryUrl}}\" }")
          echo "::set-output name=response::$token"
  
  comment-on-issue:
    runs-on: ubuntu-latest
    needs: curl-stmt
    permissions: 
      issues: write
    steps:
      - name: add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Locus suggests these are the commits that most likely caused the bug:
            ${{ needs.curl-stmt.outputs.response_info }}
            |< Most likely --------------------- Least likely >|
