name: Dog Facts API 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types:
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:


  info-dump:
    runs-on: ubuntu-latest
    steps:
    - name: $github
      run:   echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        
  curl-stmt:
    runs-on: ubuntu-latest
    outputs:
      dog_fact: ${{ steps.get-token.outputs.dog_fact }}
    steps: 
      - id: get-token
        run: |
          token=$( curl https://dog-api.kinduff.com/api/facts?number=1 | jq '.facts[]')
          echo "::set-output name=dog_fact::$token"
  
  comment-on-issue:
    runs-on: ubuntu-latest
    needs: curl-stmt
    permissions: 
      issues: write
    steps:
      - name: add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ needs.curl-stmt.outputs.dog_fact }}
            "Issue title: ${{ github.event.issue.title }}"
            "Issue bodye: ${{ github.event.issue.body }}"
