name: requestAction

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types:
      - opened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://dog-facts-api.herokuapp.com/api/v1/resources/dogs?number=1"
      - name: Show Response
        run: echo ${{ steps.myRequest.outputs.response }}
